### Login User
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "joaopedrosantiago1103@gmail.com",
  "password": "JPHP1234"
}

### Create User
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "JPHP",
  "email": "joaopedrosantiago1103@gmail.com",
  "password": "JPHP1234"
}

### Test Endpoint
GET http://localhost:8080/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlNWQyNDZiNi03MjgyLTQ4ZmYtYWZhMC02ZTVjZmQ5NzY4YmMiLCJzdWIiOiJqb2FvcGVkcm9zYW50aWFnbzExMDNAZ21haWwuY29tIiwiZXhwIjoxNzYyMzcyMjI0LCJpYXQiOjE3NjIzNjg2MjR9.eZZK0w2JsK_qtMEW-i-o_x-Nbkq2RqLZAGld-TZNaV8

